services:
    adsb-client:
        container_name: adsb-client
        build:
          context: .
          dockerfile: Dockerfile
        environment:
          - TZ=${TZ} # Sets the timezone of the image (see the README.md)
        devices:
          - /dev/bus/usb/001/004:/dev/bus/usb/001/004  # Map the RTL-SDR device to the container
        ports:
          - 3000:3000